### ISSUE TITLE
Cross reference `package.json` with `yarn.lock`

### ISSUE THREAD

**Issue by HonkingGoose** [HonkingGoose/renovate-issue-7536#3]
Checklist:

- [x] dependencies comparison
- [x] optional dependencies comparison
- [x] devDependencies comparison

**Comment by HonkingGoose** [comment]
Hi @rarkins,

I've made a draft version of the comparison between `package.json` and `yarn.lock` for issue 7536 at `renovatebot/renovate`.

Can you please review my work at https://github.com/HonkingGoose/renovate-issue-7536/blob/main/cross-reference.md and tell me what you think of it?

My repository readme has all the links you need to see what I'm basing my work on: https://github.com/HonkingGoose/renovate-issue-7536/blob/main/README.md

It's probably easiest if you fork the repository and make changes in the file and open a PR with your remarks/changes.
I'll stay away from editing this file, so that you have free reign to make your edits without getting into merge conflicts... 😄 

Greetings HonkingGoose

**Comment by rarkins** [comment]
I think the "not in diff" message is a bit too noisy. Did you consider leaving it out? I would probably lean towards having a verbose table only for direct dependencies and for transitive dependencies having only a few lists, like:

- Added transitive dependencies: foo@1.1.0, bar@1.2.1, ...
- Removed transitive dependencies: abc, def
- Updated transitive dependencies: ?? (a list may not work as well here)

Another challenge is that dependencies can appear multiple times, so it's not quite as simple as I wrote above.

**Comment by HonkingGoose** [comment]
## Removed not in diff message

> I think the "not in diff" message is a bit too noisy. Did you consider leaving it out?

It's gone now. 😉 

## Making sure we're on the same page

I needed to look up what direct and transitive dependencies are, I've found the following definitions:

> A direct dependency is one that is explicitly listed in your own `package.json` file — a dependency that your project/package uses directly in code or in an npm run script.

> A transitive dependency is one that is **not** explicitly listed in your own `package.json` file — a dependency that comes from anywhere in the tree of your direct dependencies’ dependencies.

Link to source for the definitions https://blog.npmjs.org/post/145724408060/dealing-with-problematic-dependencies-in-a

Is this what you mean with direct/transitive dependencies?

## Verbose table for direct dependencies

I think dependencies listed in `package.json` as `dependencies` are direct dependencies?
I think `devDependencies` and `optionalDependencies` in the `package.json` are "direct dependencies" as well? At least if I'm understanding the npm definition correctly...

I'm not sure what kind of change you want me to make with the verbose table... 😕 
Can you explain what kind of verbose table you would like?

## List for transitive dependencies

I'm still a bit fuzzy on what this means:

- Added transitive dependencies: foo@1.1.0, bar@1.2.1, ...
- Removed transitive dependencies: abc, def
- Updated transitive dependencies: ?? (a list may not work as well here)
- Appears multiple times

Can you maybe make one example of what you want me to do, then I can use that example as a template for the rest of my work. 😄

**Comment by rarkins** [comment]
> Is this what you mean with direct/transitive dependencies?

Yes

> I think dependencies listed in `package.json` as `dependencies` are direct dependencies?
> I think `devDependencies` and `optionalDependencies` in the `package.json` are "direct dependencies" as well? At least if I'm understanding the npm definition correctly...

Yes, that's correct

> I'm not sure what kind of change you want me to make with the verbose table... 😕
> Can you explain what kind of verbose table you would like?

Actually your current approach *is* what I meant by verbose. I was proposing less information for transitive dependencies.

For transitive,

- Added packages (we can include version number but it's not too important)
- Removed packages (ones removed altogether)
- Modified packages (can be a single instance with changed version, but can also be additional versions added or some removed)
